modLoader="javafml"
loaderVersion="[27,)"

[[mods]]
  modId="octechnics"
  version="1.0.0"
  displayName="OC Technic Factories"
  authors="ProgramCrafter"
  credits="Thanks eu_tomat for help with installing Forge"
  description='''
  This mod adds factory blocks (furnaces, crafting tables, etc) which can interact with OpenComputers.
  '''
  
  [[dependencies.octechnics]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.octechnics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"